title: "LegalFiles"
email: contacto+legalfiles@pabloarrabal.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Pablo
paginate: 30
disqus: 'demowebsite'
locale: es_es
lang: es_es
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  Pablo:
    name: Pablo Arrabal Espinosa
    display_name: Nuoframework
    avatar: 'assets/images/pablo.jpg'
    email: contacto+legalfiles@pabloarrabal.com
    web: https://pabloarrabal.com
    twitter: https://x.com/nuoframework
    description: "Autor de pabloarrabal.com, CEO y Creador de LegalFiles"

# Social
social:
  instagram: https://www.instagram.com/nuoframework
  facebook: https://www.facebook.com/people/Nuoframework/61554763833872/
  twitter: https://x.com/nuoframework

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives